/**
 * SmartShaadi Backlink Agent — GitHub Push API
 * File: app/api/github-push/route.ts
 *
 * Backlink leads ko markdown format mein SmartShaadi.ai repo mein push karta hai
 * Target file: backlink_leads.md in smartshaadi repo root
 */

import { NextRequest } from 'next/server';
import { type BacklinkLead } from '@/lib/india-seo-data';

export const runtime = 'edge';

// ─── MARKDOWN GENERATOR ───────────────────────────────────────────────────────

function generateMarkdown(leads: BacklinkLead[], runDate: string): string {
  const highValue = leads.filter(l => l.relevanceScore >= 70);
  const byStrategy = leads.reduce((acc, l) => {
    acc[l.strategy] = (acc[l.strategy] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const byCity = leads.reduce((acc, l) => {
    acc[l.city] = (acc[l.city] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return `# SmartShaadi Backlink Leads — Auto-Generated

> **Last Updated:** ${runDate}
> **Total Leads:** ${leads.length} | **High-Value (70+):** ${highValue.length}
> **Generated by:** SmartShaadi Backlink Agent (Groq + Serper)

---

## 📊 Summary

### By Strategy
${Object.entries(byStrategy)
  .sort((a, b) => b[1] - a[1])
  .map(([strategy, count]) => `- **${strategy}**: ${count} opportunities`)
  .join('\n')}

### By City
${Object.entries(byCity)
  .sort((a, b) => b[1] - a[1])
  .map(([city, count]) => `- **${city}**: ${count} leads`)
  .join('\n')}

---

## 🏆 High-Value Leads (Score ≥ 70)

${highValue
  .sort((a, b) => b.relevanceScore - a.relevanceScore)
  .map(lead => `### ${lead.title}
- **URL:** ${lead.url}
- **Strategy:** \`${lead.strategy}\`
- **Relevance Score:** ${lead.relevanceScore}/100
- **City:** ${lead.city}, ${lead.state}
- **DA Estimate:** ${lead.da || 'Unknown'}
- **Why:** ${lead.reasoning}
- **Status:** ${lead.status}
- **Snippet:** ${lead.snippet.slice(0, 150)}...

`).join('')}

---

## 📋 All Leads

| # | URL | Strategy | Score | City | Status |
|---|-----|----------|-------|------|--------|
${leads
  .sort((a, b) => b.relevanceScore - a.relevanceScore)
  .map((lead, i) =>
    `| ${i + 1} | [${lead.title.slice(0, 40)}](${lead.url}) | ${lead.strategy} | ${lead.relevanceScore} | ${lead.city} | ${lead.status} |`
  ).join('\n')}

---

## 🎯 Action Plan

### Immediate (This Week)
${highValue
  .filter(l => ['Guest Post', 'Directory Listing'].includes(l.strategy))
  .slice(0, 5)
  .map((l, i) => `${i + 1}. **${l.strategy}** on [${l.url}](${l.url}) — Score: ${l.relevanceScore}`)
  .join('\n') || 'No immediate actions found'}

### Medium Term (This Month)  
${highValue
  .filter(l => ['Quora Answer', 'Forum Comment', 'Blog Comment'].includes(l.strategy))
  .slice(0, 5)
  .map((l, i) => `${i + 1}. **${l.strategy}** on [${l.url}](${l.url}) — ${l.reasoning}`)
  .join('\n') || 'No medium-term actions found'}

---

*Auto-generated by SmartShaadi Backlink Agent. Do not edit manually.*
*Next run: See GitHub Actions schedule*
`;
}

// ─── GITHUB PUSH ──────────────────────────────────────────────────────────────

async function pushToGitHub(content: string, commitMessage: string): Promise<{
  success: boolean;
  sha?: string;
  url?: string;
  error?: string;
}> {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_REPO_OWNER || 'muahshi';
  const repo  = process.env.GITHUB_REPO_NAME  || 'SmartShaadi.ai';
  const filePath = 'backlink_leads.md';

  if (!token) throw new Error('GITHUB_TOKEN not set');

  const apiBase = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;

  // Step 1: Get current file SHA (needed for update)
  let currentSha: string | undefined;
  try {
    const getRes = await fetch(apiBase, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    });
    if (getRes.ok) {
      const existing = await getRes.json();
      currentSha = existing.sha;
    }
  } catch {
    // File doesn't exist yet — that's fine
  }

  // Step 2: Create or update file
  const body: Record<string, unknown> = {
    message: commitMessage,
    content: Buffer.from(content).toString('base64'),
    branch: 'main',
  };
  if (currentSha) body.sha = currentSha;

  const putRes = await fetch(apiBase, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify(body),
  });

  if (!putRes.ok) {
    const err = await putRes.json();
    throw new Error(`GitHub API error: ${putRes.status} — ${JSON.stringify(err)}`);
  }

  const result = await putRes.json();
  return {
    success: true,
    sha: result.content?.sha,
    url: result.content?.html_url,
  };
}

// ─── ROUTE HANDLER ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const { leads, runDate } = await req.json() as {
      leads: BacklinkLead[];
      runDate: string;
    };

    if (!leads || leads.length === 0) {
      return Response.json({ error: 'No leads provided' }, { status: 400 });
    }

    // Generate markdown
    const markdown = generateMarkdown(leads, runDate);

    // Push to GitHub
    const commitMsg = `🔗 Backlink Agent: ${leads.length} leads found on ${runDate.split('T')[0]}`;
    const result = await pushToGitHub(markdown, commitMsg);

    return Response.json({
      success: true,
      leadsCount: leads.length,
      highValue: leads.filter(l => l.relevanceScore >= 70).length,
      githubUrl: result.url,
      sha: result.sha,
      message: `✅ ${leads.length} leads GitHub pe push ho gaye!`,
    });

  } catch (err) {
    console.error('GitHub push error:', err);
    return Response.json(
      { success: false, error: (err as Error).message },
      { status: 500 }
    );
  }
}

